# Generated by Django 5.2.1 on 2025-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stadiums",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, null=True)),
                ("state", models.CharField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="stadiums/"),
                ),
                (
                    "diagram",
                    models.ImageField(blank=True, null=True, upload_to="stadiums/"),
                ),
            ],
        ),
    ]
