# Generated by Django 5.2.1 on 2025-05-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("stadiums", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lineups",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("first_pos", models.CharField()),
                ("second_pos", models.CharField()),
                ("third_pos", models.CharField()),
                ("fourth_pos", models.CharField()),
                ("fifth_pos", models.CharField()),
                ("sixth_pos", models.CharField()),
                ("seventh_pos", models.CharField()),
                ("eighth_pos", models.CharField()),
                ("ninth_pos", models.CharField()),
                (
                    "eighth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_8th",
                        to="players.players",
                    ),
                ),
                (
                    "fifth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_5th",
                        to="players.players",
                    ),
                ),
                (
                    "first",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_1st",
                        to="players.players",
                    ),
                ),
                (
                    "fourth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_4th",
                        to="players.players",
                    ),
                ),
                (
                    "ninth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_9th",
                        to="players.players",
                    ),
                ),
                (
                    "second",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_2nd",
                        to="players.players",
                    ),
                ),
                (
                    "seventh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_7th",
                        to="players.players",
                    ),
                ),
                (
                    "sixth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_6th",
                        to="players.players",
                    ),
                ),
                (
                    "third",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups_3rd",
                        to="players.players",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                (
                    "common_lineup_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_common",
                        to="teams.lineups",
                    ),
                ),
                (
                    "lineup3_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_lu3",
                        to="teams.lineups",
                    ),
                ),
                (
                    "lineup4_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_lu4",
                        to="teams.lineups",
                    ),
                ),
                (
                    "lineup5_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_lu5",
                        to="teams.lineups",
                    ),
                ),
                (
                    "stadium_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="stadiums.stadiums",
                    ),
                ),
                (
                    "vs_l_lineup_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_vs_l",
                        to="teams.lineups",
                    ),
                ),
                (
                    "vs_r_lineup_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_vs_r",
                        to="teams.lineups",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                (
                    "hat_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                (
                    "team_serial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teams.teams",
                    ),
                ),
            ],
        ),
    ]
