# Generated by Django 5.2.1 on 2025-05-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teams",
            name="name",
        ),
        migrations.AddField(
            model_name="teams",
            name="first_name",
            field=models.CharField(default="All Time"),
        ),
        migrations.AddField(
            model_name="teams",
            name="team_name",
            field=models.CharField(default="Team"),
        ),
    ]
