# Generated by Django 5.2.1 on 2025-07-07 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_alter_playerpositionrating_options_and_more"),
        ("teams", "0002_remove_teams_name_teams_first_name_teams_team_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "allow_dh",
                    models.BooleanField(
                        default=False,
                        help_text="Check to use a 9-player (DH) lineup; leave unchecked for an 8-player non-DH lineup.",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="teams.teams",
                    ),
                ),
            ],
            options={
                "ordering": ["team", "name"],
                "unique_together": {("team", "name")},
            },
        ),
        migrations.CreateModel(
            name="TeamLineupEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batting_order", models.PositiveSmallIntegerField()),
                (
                    "field_position",
                    models.CharField(
                        choices=[
                            ("P", "P"),
                            ("C", "C"),
                            ("1B", "1B"),
                            ("2B", "2B"),
                            ("3B", "3B"),
                            ("SS", "SS"),
                            ("LF", "LF"),
                            ("CF", "CF"),
                            ("RF", "RF"),
                            ("DH", "DH"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="teams.lineup",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.players",
                    ),
                ),
            ],
            options={
                "ordering": ["batting_order"],
                "unique_together": {
                    ("lineup", "batting_order"),
                    ("lineup", "field_position"),
                },
            },
        ),
    ]
