# Generated by Django 5.2.1 on 2025-06-19 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0007_alter_playerpositionrating_options_and_more"),
        ("teams", "0002_remove_teams_name_teams_first_name_teams_team_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_played", models.DateField()),
                ("home_score", models.PositiveSmallIntegerField()),
                ("away_score", models.PositiveSmallIntegerField()),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="teams.teams",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.competition",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="teams.teams",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InningScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField()),
                ("runs", models.PositiveSmallIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.game"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.teams"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leagues",
                        to="stats.competition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="stats.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStatLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pa", models.PositiveSmallIntegerField(default=0)),
                ("ab", models.PositiveSmallIntegerField(default=0)),
                ("h", models.PositiveSmallIntegerField(default=0)),
                ("r", models.PositiveSmallIntegerField(default=0)),
                ("rbi", models.PositiveSmallIntegerField(default=0)),
                ("bb", models.PositiveSmallIntegerField(default=0)),
                ("k", models.PositiveSmallIntegerField(default=0)),
                ("hr", models.PositiveSmallIntegerField(default=0)),
                ("sb", models.PositiveSmallIntegerField(default=0)),
                ("cs", models.PositiveSmallIntegerField(default=0)),
                ("ip", models.FloatField(default=0)),
                ("er", models.PositiveSmallIntegerField(default=0)),
                ("h_allowed", models.PositiveSmallIntegerField(default=0)),
                ("bb_allowed", models.PositiveSmallIntegerField(default=0)),
                ("k_thrown", models.PositiveSmallIntegerField(default=0)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Win"),
                            ("L", "Loss"),
                            ("S", "Save"),
                            ("", "None"),
                        ],
                        default="",
                        max_length=1,
                    ),
                ),
                ("po", models.PositiveSmallIntegerField(default=0)),
                ("a", models.PositiveSmallIntegerField(default=0)),
                ("e", models.PositiveSmallIntegerField(default=0)),
                ("position", models.CharField(max_length=3)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.players",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.teams"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField()),
                ("position", models.CharField(max_length=3)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.game"
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subs_in",
                        to="players.players",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subs_out",
                        to="players.players",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.teams"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineupEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batting_order", models.PositiveSmallIntegerField()),
                ("fielding_position", models.CharField(max_length=3)),
                ("is_starting", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.players",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.teams"
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "team", "batting_order", "is_starting")},
            },
        ),
        migrations.CreateModel(
            name="TeamStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.competition",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.division",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.teams"
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "team")},
            },
        ),
    ]
