# Generated by Django 5.2.1 on 2025-06-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
        ("teams", "0002_remove_teams_name_teams_first_name_teams_team_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inningscore",
            unique_together={("game", "team", "inning")},
        ),
    ]
