# Generated by Django 5.2.1 on 2025-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_inningscore_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("final", "FInal")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
