# Generated by Django 5.2.1 on 2025-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineupentry",
            name="batting_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
