# Generated by Django 5.2.1 on 2025-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_lineupentry_batting_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerstatline",
            old_name="k",
            new_name="balk",
        ),
        migrations.RenameField(
            model_name="playerstatline",
            old_name="pa",
            new_name="doubles",
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="dp",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="hb",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="hbp",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="hra",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="ibb",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="pb",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="sf",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="so",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="triples",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="wp",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
