# Generated by Django 5.2.1 on 2025-06-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_rename_k_playerstatline_balk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstatline",
            name="ip",
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="ip_outs",
            field=models.IntegerField(default=0),
        ),
    ]
