# Generated by Django 5.2.1 on 2025-06-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_remove_playerstatline_ip_playerstatline_ip_outs"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatline",
            name="ra",
            field=models.IntegerField(default=0),
        ),
    ]
