# Generated by Django 5.2.1 on 2025-06-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0007_playerstatline_ra"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="has_structure",
            field=models.BooleanField(
                default=False,
                help_text="Check if this competition uses leagues/divisions",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="abbreviation",
            field=models.CharField(default=False, max_length=5),
            preserve_default=False,
        ),
    ]
