# Generated by Django 5.2.1 on 2025-06-24 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0008_competition_has_structure_league_abbreviation"),
        ("teams", "0002_remove_teams_name_teams_first_name_teams_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="league",
            name="has_divisions",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="competition",
            name="has_structure",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="league",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="TeamEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_entries",
                        to="stats.competition",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_entries",
                        to="stats.division",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_entries",
                        to="stats.league",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_entries",
                        to="teams.teams",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "league", "division", "team")},
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                related_name="competitions", through="stats.TeamEntry", to="teams.teams"
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="teams",
            field=models.ManyToManyField(
                related_name="divisions", through="stats.TeamEntry", to="teams.teams"
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="teams",
            field=models.ManyToManyField(
                related_name="leagues", through="stats.TeamEntry", to="teams.teams"
            ),
        ),
    ]
