# Generated by Django 5.2.1 on 2025-06-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0009_competition_abbreviation_league_has_divisions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatline",
            name="threw",
            field=models.BooleanField(
                default=False, help_text="Did this player pitch in the game?"
            ),
        ),
    ]
