# Generated by Django 5.2.1 on 2025-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0010_playerstatline_threw"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="venue",
            field=models.CharField(
                blank=True, help_text="Stadium or ballpark", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="weather",
            field=models.CharField(
                blank=True, help_text="Wind, rain, etc.", max_length=100
            ),
        ),
    ]
