# Generated by Django 5.2.1 on 2025-07-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0011_game_venue_game_weather"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
