# Generated by Django 5.2.1 on 2025-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0012_alter_game_away_score_alter_game_home_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_score",
            field=models.IntegerField(default=0),
        ),
    ]
