# Generated by Django 5.2.1 on 2025-07-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0013_alter_game_away_score_alter_game_home_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatline",
            name="runners_caught",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstatline",
            name="sb_allowed",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
