# Generated by Django 5.2.1 on 2025-07-03 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0007_alter_playerpositionrating_options_and_more"),
        ("stats", "0010_playerstatline_threw"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField(default=1)),
                ("is_top", models.BooleanField(default=True)),
                ("outs", models.PositiveSmallIntegerField(default=0)),
                ("batter_idx", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.game"
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "status")},
            },
        ),
        migrations.CreateModel(
            name="PlayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1B", "Single"),
                            ("2B", "Double"),
                            ("3B", "Triple"),
                            ("HR", "Home Run"),
                            ("BB", "Walk"),
                            ("K", "Strikeout"),
                            ("OUT", "Other Out"),
                        ],
                        max_length=10,
                    ),
                ),
                ("inning", models.PositiveSmallIntegerField()),
                ("is_top", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "batter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="players.players",
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="players.players",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="games.gamesession",
                    ),
                ),
            ],
        ),
    ]
