# Generated by Django 5.2.1 on 2025-07-03 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("players", "0007_alter_playerpositionrating_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="pitcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game_sessions",
                to="players.players",
            ),
        ),
    ]
