# Generated by Django 5.2.1 on 2025-07-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_gamesession_pitcher"),
        ("players", "0007_alter_playerpositionrating_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamesession",
            name="pitcher",
        ),
        migrations.AddField(
            model_name="gamesession",
            name="away_pitcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="players.players",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="home_pitcher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="players.players",
            ),
        ),
    ]
