# Generated by Django 5.2.1 on 2025-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_remove_gamesession_pitcher_gamesession_away_pitcher_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamesession",
            old_name="batter_idx",
            new_name="away_batter_idx",
        ),
        migrations.AddField(
            model_name="gamesession",
            name="home_batter_idx",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
