# Generated by Django 5.2.1 on 2025-07-05 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_rename_batter_idx_gamesession_away_batter_idx_and_more"),
        ("players", "0007_alter_playerpositionrating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="runner_on_first",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="players.players",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="runner_on_second",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="players.players",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="runner_on_third",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="players.players",
            ),
        ),
    ]
