# Generated by Django 5.2.1 on 2025-07-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_playevent_result_sessioninningscore"),
        ("players", "0007_alter_playerpositionrating_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSessionStatLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ab", models.PositiveSmallIntegerField(default=0)),
                ("h", models.PositiveSmallIntegerField(default=0)),
                ("r", models.PositiveSmallIntegerField(default=0)),
                ("rbi", models.PositiveSmallIntegerField(default=0)),
                ("bb", models.PositiveSmallIntegerField(default=0)),
                ("hbp", models.PositiveSmallIntegerField(default=0)),
                ("so", models.PositiveSmallIntegerField(default=0)),
                ("sb", models.PositiveSmallIntegerField(default=0)),
                ("cs", models.PositiveSmallIntegerField(default=0)),
                ("dp", models.PositiveSmallIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.players",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_stats",
                        to="games.gamesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "player")},
            },
        ),
    ]
