# Generated by Django 5.2.1 on 2025-07-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_alter_playevent_result"),
        ("players", "0007_alter_playerpositionrating_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayEvent",
            new_name="AtBatResult",
        ),
        migrations.CreateModel(
            name="StatDelta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_field",
                    models.CharField(
                        choices=[
                            ("ab", "At Bats"),
                            ("h", "Hits"),
                            ("r", "Runs"),
                            ("rbi", "RBIs"),
                            ("bb", "Walks"),
                            ("hbp", "HBP"),
                            ("so", "Strikeouts"),
                            ("sb", "Stolen Bases"),
                            ("cs", "Caught Stealing"),
                            ("dp", "Double Plays"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_deltas",
                        to="games.atbatresult",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="players.players",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlayerSessionStatLine",
        ),
        migrations.AddIndex(
            model_name="statdelta",
            index=models.Index(
                fields=["player", "stat_field"], name="games_statd_player__7bd6eb_idx"
            ),
        ),
    ]
