# Generated by Django 5.2.1 on 2025-05-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayerPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="players/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Players",
            fields=[
                ("serial", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(default="None")),
                ("last_name", models.CharField(default="None")),
                ("positions", models.CharField(default="None")),
                ("bats", models.CharField(default="R/L", max_length=3)),
                ("throws", models.CharField(default="R/L")),
                ("uni_num", models.IntegerField(blank=True, null=True)),
                ("defense", models.CharField(default="84")),
                ("offense", models.CharField(blank=True, null=True)),
                ("pitching", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
