# Generated by Django 5.2.1 on 2025-05-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="team_serial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playerpicture",
            name="player_serial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.players"
            ),
        ),
    ]
