# Generated by Django 5.2.1 on 2025-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="players",
            name="year",
            field=models.CharField(default="career"),
        ),
    ]
