# Generated by Django 5.2.1 on 2025-06-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_players_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="players",
            old_name="defense",
            new_name="defense_1",
        ),
        migrations.RenameField(
            model_name="players",
            old_name="positions",
            new_name="defense_2",
        ),
        migrations.AddField(
            model_name="players",
            name="bat_prob_hit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_3",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_4",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_5",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_6",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_7",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_8",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="defense_9",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="pitch_ctl",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="pitch_prob_hit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="players",
            name="position_1",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_2",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_3",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_4",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_5",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_6",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_7",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_8",
            field=models.CharField(default="None"),
        ),
        migrations.AddField(
            model_name="players",
            name="position_9",
            field=models.CharField(default="None"),
        ),
    ]
