# Generated by Django 5.2.1 on 2025-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_add_positions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerpositionrating",
            options={"ordering": ["position_order"]},
        ),
        migrations.AddField(
            model_name="playerpositionrating",
            name="position_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
